#!/bin/sh

CONF_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/hmq

BIN_DIR=$ADDON_DIR/bin

Stop () {
    echo -n "Stopping hmq MQTT broker: "
    start-stop-daemon -K -q -p /var/run/hmq.pid && echo "OK"
}

Start () {
    echo -n "Starting hmq MQTT broker: "
    start-stop-daemon -S -b -m -p /var/run/hmq.pid --exec $ADDON_DIR/bin/hmq && echo "OK"
}

case "$1" in

  stop)
    Stop
  ;;

  start)
    Start
  ;;

  restart)
    Stop
    sleep 3
    Start
  ;;

  info)
    echo "Info: <center><a href=\"https://github.com/fhmq/hmq\" target=\"_blank\">hmq MQTT Broker addon</a></center>"
    echo "Name: hmq MQTT broker"
    echo "Version: 1.4"
    echo "Update: /addons/hmq/update_check.cgi"
    echo "Operations: uninstall restart"
  ;;

  uninstall)
     Stop
     rm /var/run/hmq.pid
     rm $CONF_DIR/rc.d/hmq
     rm $BIN_DIR/hmq*
     rm $CONF_DIR/addons/www/hmq
     rm -r $ADDON_DIR
  ;;

  *)
    echo "Usage: hmq {start|stop|restart|info|uninstall}" >&2
    exit 1
  ;;

esac



exit 0
